/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function findImports(filePaths: Array<string>, callback: (result: {file: string, importExpr: string}) => void): void
export class ImportResult {
  file: string
  importExpr: string
}
